

import type { Metadata } from "next";
import { Exo, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import FirstNav from "./_component/firstNav/FirstNav";
import { Toaster } from "@/components/ui/sonner"
import { ToastContainer, toast } from 'react-toastify';
import SessionProviderContext from "./_component/sessionProvider/SessionProviderContext";
import NumbercontextProvider  from './../context/cartcontxt';

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700","800"], 
  variable: "--font-exo", 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Flash Cart by me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}  >
        <SessionProviderContext>
        <NumbercontextProvider>
        <FirstNav/>
        <Navbar/>
        {children}
        <ToastContainer />
        <Footer/>
        </NumbercontextProvider>
        </SessionProviderContext>
        </body>
    </html>
  );
}
